---
- hosts: all
  become: yes
  tasks:
    - name: copying docker-compose with playbook
      copy:
        src: ../../docker/docker-compose.yml
        dest: "/home/{{ansible_user}}/docker/"
        owner: "{{ansible_user}}"
        group: "{{ansible_user}}"
        mode: 0777
        force: true
    
    - name: copying env with playbook
      copy:
        src: ../../docker/.env
        dest: "/home/{{ansible_user}}/docker/"
        owner: "{{ansible_user}}"
        group: "{{ansible_user}}"
        mode: 0777
        force: true

    - name: run docker-compose up
      shell: 
        cmd: "docker-compose -f docker-compose.yml up -d"
        chdir: "/home/{{ansible_user}}/docker/"